### PR TITLE
add SPDX

### PR DESCRIPTION
**Pull request by NoahZinsmeister**

### CODE REVIEW

**Comment by moodysalem** [comment]
the repo is GPLv3, why unlicense some contracts?

**Comment by NoahZinsmeister** [comment]
well i only did it for the test contracts, because they're not distributed. just thought it felt a bit weird to have them also be GPL, but happy to do it if you think it makes more sense

**Comment by moodysalem** [comment]
oh, i missed that, if someone forks the software though and makes improvements they will need the old test suite, so mixed licensing is kind of confusing in that case

**Comment by NoahZinsmeister** [comment]
yeah fair enough, GPL it is!

**Review by moodysalem — APPROVED** [review]

**Pull request merged**
